import { packImage, section, type PackTemplate } from './packTypes';

const red = '#a6192e';
const ink = '#202b32';
const blue = '#074f7c';
const card = { fontSize: 16, padding: 14, lineHeight: 1.2, borderWidth: 0, color: ink };
const plain = { ...card, backgroundColor: 'transparent' };
const brand = () =>
  section(
    'text',
    'Peer Mentor Hub',
    24,
    18,
    768,
    38,
    { role: 'header', body: 'SFU PEER MENTOR HUB  ·  STUDENTS SUPPORTING STUDENTS' },
    { ...plain, fontSize: 16, fontWeight: 'bold', padding: 8 },
  );

/** Designs reconstructed from reference images 11–15, with editable sample content. */
export const thirdTemplates: PackTemplate[] = [
  {
    id: 'recreation',
    name: 'Get Active — Recreation',
    description:
      'A bold blue recreation guide with an editable activity table and community cards.',
    reference: '11_get_active_recreation.png',
    category: 'Recreation',
    theme: 'Recreation blue',
    background: '#edf5f5',
    sections: [
      brand(),
      section(
        'title',
        'Title Banner',
        24,
        70,
        768,
        118,
        { title: 'GET ACTIVE\nAT SFU', accentColor: blue, radius: 0 },
        { ...card, fontSize: 43, lineHeight: 1.04, color: '#ffffff', padding: 12 },
      ),
      section(
        'hero',
        'Hero Image',
        24,
        200,
        768,
        198,
        { radius: 4 },
        { src: packImage('recreation'), borderWidth: 0 },
      ),
      section(
        'table',
        'Drop-In Activities',
        24,
        412,
        504,
        290,
        {
          title: 'DROP-IN ACTIVITIES',
          subtitle: 'Sample schedule · replace before sharing',
          columns: ['Activity', 'Day', 'Time', 'Location'],
          rows: [
            ['Activity 1', 'Add day', 'Add time', 'Add room'],
            ['Activity 2', 'Add day', 'Add time', 'Add room'],
            ['Activity 3', 'Add day', 'Add time', 'Add room'],
            ['Activity 4', 'Add day', 'Add time', 'Add room'],
          ],
          accentColor: blue,
          headerColor: blue,
          rowColor: '#edf3f7',
          radius: 12,
        },
        { ...card, padding: 12 },
      ),
      section(
        'list',
        'Facilities',
        540,
        412,
        252,
        290,
        {
          title: 'FACILITIES',
          icon: '◇',
          accentColor: blue,
          items: [
            'Explore recreation spaces',
            'Check access requirements',
            'Confirm opening hours',
            'Add a facility link',
          ],
        },
        { ...card, backgroundColor: '#ffffff' },
      ),
      section(
        'info',
        'Programs',
        24,
        716,
        248,
        156,
        {
          title: 'PROGRAMS',
          icon: '◎',
          body: 'Add a program you want to try. Confirm registration details with SFU Recreation.',
          accentColor: blue,
        },
        { ...card, backgroundColor: '#f7fbfc' },
      ),
      section(
        'info',
        'Community',
        284,
        716,
        248,
        156,
        {
          title: 'COMMUNITY',
          icon: '♡',
          body: 'Invite a friend, share an activity, and find ways to get involved.',
          accentColor: red,
        },
        { ...card, backgroundColor: '#fff8f8' },
      ),
      section(
        'info',
        'Stay Updated',
        544,
        716,
        248,
        156,
        {
          title: 'STAY UPDATED',
          icon: '▦',
          body: 'Replace this card with a current Resource Hub entry before sharing.',
          accentColor: '#4e478c',
        },
        { ...card, backgroundColor: '#f8f7fe' },
      ),
      section(
        'image',
        'Mountain Footer Image',
        24,
        886,
        768,
        100,
        { role: 'footer', radius: 0 },
        { src: packImage('mountain'), borderWidth: 0 },
      ),
      section(
        'footer',
        'Footer',
        24,
        998,
        768,
        34,
        { body: 'PEER MENTOR HUB  ·  ADD YOUR CONTACT OR OFFICIAL RESOURCE LINK' },
        { ...plain, fontSize: 13, color: blue, padding: 8 },
      ),
    ],
  },
  {
    id: 'courses-campus',
    name: 'Course Planning — Campus',
    description:
      'A campus-inspired planning layout with three pathways, useful links and a checklist.',
    reference: '12_course_planning_photo.png',
    category: 'Planning',
    theme: 'Campus cream and crimson',
    background: '#f7f6ef',
    sections: [
      brand(),
      section(
        'hero',
        'Hero Image',
        466,
        72,
        326,
        294,
        { radius: 0 },
        { src: packImage('campus'), borderWidth: 0 },
      ),
      section(
        'title',
        'Title Banner',
        24,
        72,
        430,
        166,
        { title: 'COURSE\nPLANNING', accentColor: red, bannerStyle: 'underline' },
        { ...plain, fontSize: 48, lineHeight: 1.1, padding: 12 },
      ),
      section(
        'text',
        'Planning Introduction',
        24,
        250,
        430,
        116,
        { role: 'header', body: 'Explore your options.\nPlan your next term.' },
        { ...plain, fontSize: 24, fontWeight: 'bold', padding: 12 },
      ),
      section(
        'info',
        'Explore Courses',
        24,
        382,
        248,
        184,
        {
          title: 'EXPLORE COURSES',
          icon: '⌕',
          body: 'Browse the Course Planner. Add a course card or editable offering table.',
          accentColor: red,
        },
        { ...card, backgroundColor: '#ffffff' },
      ),
      section(
        'info',
        'Plan Ahead',
        284,
        382,
        248,
        184,
        {
          title: 'PLAN AHEAD',
          icon: '▣',
          body: 'List courses that interest you and questions to discuss with an advisor.',
          accentColor: red,
        },
        { ...card, backgroundColor: '#ffffff' },
      ),
      section(
        'info',
        'Build Your Path',
        544,
        382,
        248,
        184,
        {
          title: 'BUILD YOUR PATH',
          icon: '◇',
          body: 'Compare options with your goals. Keep a flexible plan for the term.',
          accentColor: '#326144',
        },
        { ...card, backgroundColor: '#eef6ee' },
      ),
      section(
        'list',
        'Useful Resources',
        24,
        580,
        328,
        270,
        {
          title: 'USEFUL RESOURCES',
          icon: '↗',
          accentColor: '#006a70',
          items: [
            'Academic Calendar',
            'Program requirements',
            'Course outlines',
            'Enrollment information',
            'Academic advising',
          ],
        },
        { ...card, backgroundColor: '#edf7f8' },
      ),
      section(
        'checklist',
        'Tips for Success',
        364,
        580,
        428,
        270,
        {
          title: 'TIPS FOR SUCCESS',
          icon: '✓',
          accentColor: '#70530d',
          items: [
            'Review prerequisites',
            'Plan core and elective courses',
            'Confirm dates in official sources',
            'Discuss questions with an advisor',
            'Check the balance of your schedule',
            'Save a backup course option',
          ],
        },
        { ...card, backgroundColor: '#fff8e7' },
      ),
      section(
        'image',
        'Campus Outlook Image',
        24,
        864,
        768,
        120,
        { role: 'footer', radius: 0 },
        { src: packImage('mountain'), borderWidth: 0 },
      ),
      section(
        'footer',
        'Footer',
        24,
        996,
        768,
        36,
        { body: 'SFU PEER MENTOR HUB  ·  ADD YOUR CONTACT DETAILS' },
        { ...card, padding: 9, fontSize: 13, backgroundColor: red, color: '#ffffff' },
      ),
    ],
  },
  {
    id: 'safety',
    name: 'Campus Safety',
    description:
      'A calm safety guide with six support cards, mentor information and a live QR code.',
    reference: '13_campus_safety.png',
    category: 'Safety',
    theme: 'Safety crimson and blue',
    background: '#ffffff',
    sections: [
      brand(),
      section(
        'hero',
        'Hero Image',
        24,
        70,
        768,
        208,
        { radius: 0 },
        { src: packImage('campus'), borderWidth: 0 },
      ),
      section(
        'title',
        'Title Banner',
        24,
        290,
        768,
        82,
        { title: 'CAMPUS SAFETY', accentColor: red, bannerStyle: 'underline' },
        { ...plain, padding: 12, fontSize: 44 },
      ),
      section(
        'text',
        'Safety Introduction',
        24,
        378,
        768,
        38,
        { role: 'header', body: 'Keep current, official support information within reach.' },
        { ...plain, fontSize: 18, padding: 7 },
      ),
      section(
        'info',
        'Emergency',
        24,
        430,
        248,
        170,
        {
          title: 'EMERGENCY',
          icon: '!',
          body: 'Add verified emergency instructions and contact details before sharing.',
          accentColor: red,
        },
        { ...card, backgroundColor: '#fceef1' },
      ),
      section(
        'info',
        'Campus Public Safety',
        284,
        430,
        248,
        170,
        {
          title: 'CAMPUS PUBLIC SAFETY',
          body: 'Replace this card with the official Resource Hub entry. Confirm contact details.',
          accentColor: ink,
        },
        { ...card, backgroundColor: '#f0f3f5' },
      ),
      section(
        'info',
        'Safe Walk',
        544,
        430,
        248,
        170,
        {
          title: 'SAFE WALK',
          icon: '↗',
          body: 'Add current official information about availability and requesting support.',
          accentColor: blue,
        },
        { ...card, backgroundColor: '#e9f4fc' },
      ),
      section(
        'info',
        'Lost & Found',
        24,
        614,
        248,
        170,
        {
          title: 'LOST & FOUND',
          icon: '◇',
          body: 'Add the official lost-item reporting or collection instructions.',
          accentColor: ink,
        },
        { ...card, backgroundColor: '#f0f3f5' },
      ),
      section(
        'info',
        'After-Hours Help',
        284,
        614,
        248,
        170,
        {
          title: 'AFTER-HOURS HELP',
          body: 'Add current official support options and verified contact details.',
          accentColor: red,
        },
        { ...card, backgroundColor: '#fceef1' },
      ),
      section(
        'list',
        'Quick Tips',
        544,
        614,
        248,
        170,
        {
          title: 'QUICK TIPS',
          accentColor: blue,
          items: ['Save official links', 'Check contact details', 'Plan how to get help'],
        },
        { ...card, backgroundColor: '#e9f4fc' },
      ),
      section(
        'info',
        'Peer Mentor Hub Support',
        24,
        800,
        612,
        124,
        {
          title: 'SFU PEER MENTOR HUB',
          body: 'Add your mentor contact details and a short invitation to connect.',
          accentColor: ink,
        },
        { ...card, backgroundColor: '#f0f3f5' },
      ),
      section(
        'qr',
        'Safety Resource QR',
        660,
        800,
        124,
        124,
        { radius: 0 },
        { text: 'https://www.sfu.ca/', backgroundColor: '#ffffff', borderWidth: 0 },
      ),
      section(
        'footer',
        'Footer',
        24,
        940,
        768,
        92,
        {
          body: 'OFFICIAL INFORMATION FIRST\nQR links to the SFU homepage. Choose a verified resource URL before sharing.',
        },
        { ...card, fontSize: 14, padding: 18, backgroundColor: ink, color: '#ffffff' },
      ),
    ],
  },
  {
    id: 'academic',
    name: 'Academic Success',
    description:
      'A red-and-charcoal study guide with six support cards, a study plan and practical tips.',
    reference: '14_academic_success.png',
    category: 'Academic',
    theme: 'Academic editorial',
    background: '#faf7f1',
    sections: [
      brand(),
      section(
        'hero',
        'Hero Image',
        470,
        70,
        322,
        246,
        { radius: 0 },
        { src: packImage('library'), borderWidth: 0 },
      ),
      section(
        'title',
        'Title Banner',
        24,
        70,
        432,
        166,
        { title: 'ACADEMIC\nSUCCESS', accentColor: red, bannerStyle: 'underline' },
        { ...plain, fontSize: 46, lineHeight: 1.1, padding: 12 },
      ),
      section(
        'text',
        'Academic Introduction',
        24,
        248,
        432,
        68,
        { role: 'header', body: 'Study smarter.\nStay supported.' },
        { ...plain, fontSize: 20, fontWeight: 'bold', padding: 8 },
      ),
      section(
        'info',
        'Student Learning Commons',
        24,
        330,
        248,
        174,
        {
          title: 'STUDENT LEARNING COMMONS',
          body: 'Choose a verified Resource Hub entry for learning support.',
          accentColor: red,
        },
        { ...card, backgroundColor: '#f5e5e3' },
      ),
      section(
        'info',
        'Writing Support',
        284,
        330,
        248,
        174,
        {
          title: 'WRITING SUPPORT',
          icon: '✎',
          body: 'Add writing resources and questions for your next assignment.',
          accentColor: ink,
        },
        { ...card, backgroundColor: '#efede7' },
      ),
      section(
        'info',
        'Academic Advising',
        544,
        330,
        248,
        174,
        {
          title: 'ACADEMIC ADVISING',
          body: 'Add an official advising resource and your next planning question.',
          accentColor: red,
        },
        { ...card, backgroundColor: '#f5e5e3' },
      ),
      section(
        'info',
        'Research Help',
        24,
        518,
        248,
        174,
        {
          title: 'RESEARCH HELP',
          icon: '⌕',
          body: 'Collect useful search tools and library resources for your project.',
          accentColor: ink,
        },
        { ...card, backgroundColor: '#efede7' },
      ),
      section(
        'info',
        'Time Management',
        284,
        518,
        248,
        174,
        {
          title: 'TIME MANAGEMENT',
          body: 'Choose a weekly planning habit and set aside time to review it.',
          accentColor: red,
        },
        { ...card, backgroundColor: '#f5e5e3' },
      ),
      section(
        'info',
        'Exam Prep',
        544,
        518,
        248,
        174,
        {
          title: 'EXAM PREP',
          icon: '▦',
          body: 'Add review topics, practice tasks and questions to ask before the exam.',
          accentColor: ink,
        },
        { ...card, backgroundColor: '#efede7' },
      ),
      section(
        'checklist',
        'My Study Plan',
        24,
        706,
        292,
        224,
        {
          title: 'MY STUDY PLAN',
          accentColor: ink,
          items: [
            'Set one study goal',
            'Map important dates',
            'Break tasks into steps',
            'Plan time for breaks',
            'Check in with a mentor',
          ],
        },
        { ...card, backgroundColor: '#f5e5e3' },
      ),
      section(
        'list',
        'Tips for Success',
        328,
        706,
        276,
        224,
        {
          title: 'QUICK TIPS',
          accentColor: ink,
          items: [
            'Start with a small step',
            'Use campus resources',
            'Find a study routine',
            'Leave room to rest',
          ],
        },
        { ...card, backgroundColor: '#efede7' },
      ),
      section(
        'text',
        'Support QR Caption',
        616,
        706,
        176,
        52,
        { body: 'OFFICIAL\nSFU RESOURCES' },
        { ...plain, fontSize: 16, fontWeight: 'bold', align: 'center', padding: 5 },
      ),
      section(
        'qr',
        'Academic Resource QR',
        628,
        770,
        152,
        152,
        { radius: 0 },
        { text: 'https://www.sfu.ca/', backgroundColor: '#ffffff', borderWidth: 0 },
      ),
      section(
        'image',
        'Mountain Footer Image',
        24,
        942,
        768,
        58,
        { role: 'footer', radius: 0 },
        { src: packImage('mountain'), borderWidth: 0 },
      ),
      section(
        'footer',
        'Footer',
        24,
        1008,
        768,
        28,
        { body: 'SFU PEER MENTOR HUB  ·  ADD YOUR CONTACT DETAILS' },
        { ...card, padding: 6, fontSize: 12, backgroundColor: ink, color: '#ffffff' },
      ),
    ],
  },
  {
    id: 'international',
    name: 'International Students',
    description:
      'A welcoming six-color resource guide with a newcomer checklist and editable support QR.',
    reference: '15_international_students.png',
    category: 'International',
    theme: 'International community',
    background: '#ffffff',
    sections: [
      brand(),
      section(
        'title',
        'Title Banner',
        24,
        70,
        768,
        112,
        { title: 'INTERNATIONAL\nSTUDENTS', accentColor: red, radius: 0 },
        { ...card, fontSize: 38, lineHeight: 1.08, padding: 12, color: '#ffffff' },
      ),
      section(
        'hero',
        'Hero Image',
        24,
        194,
        768,
        220,
        { radius: 0 },
        { src: packImage('international'), borderWidth: 0 },
      ),
      section(
        'info',
        'International Services',
        24,
        428,
        248,
        172,
        {
          title: 'INTERNATIONAL SERVICES',
          body: 'Choose an official SFU resource for international student information.',
          accentColor: red,
        },
        { ...card, backgroundColor: '#fceef1' },
      ),
      section(
        'info',
        'Health & Insurance',
        284,
        428,
        248,
        172,
        {
          title: 'HEALTH & INSURANCE',
          body: 'Consult official SFU guidance about coverage and available support.',
          accentColor: '#387332',
        },
        { ...card, backgroundColor: '#edf7eb' },
      ),
      section(
        'info',
        'Study Permits / Immigration Information',
        544,
        428,
        248,
        172,
        {
          title: 'IMMIGRATION INFORMATION',
          body: 'Use official SFU resources for current information. This card is not legal advice.',
          accentColor: '#2462a4',
        },
        { ...card, backgroundColor: '#ebf2fc' },
      ),
      section(
        'info',
        'Housing',
        24,
        614,
        248,
        172,
        {
          title: 'HOUSING & LIVING',
          body: 'Add an official housing resource and questions for your search.',
          accentColor: '#885c00',
        },
        { ...card, backgroundColor: '#fff6df' },
      ),
      section(
        'info',
        'Community / Clubs',
        284,
        614,
        248,
        172,
        {
          title: 'COMMUNITY & CLUBS',
          body: 'Explore a club or event that interests you. Add a verified resource here.',
          accentColor: '#673494',
        },
        { ...card, backgroundColor: '#f4edfd' },
      ),
      section(
        'info',
        'Getting Started',
        544,
        614,
        248,
        172,
        {
          title: 'GETTING STARTED',
          body: 'Collect your first-term questions and choose one next step with your mentor.',
          accentColor: '#006d73',
        },
        { ...card, backgroundColor: '#e8f8f9' },
      ),
      section(
        'checklist',
        'Newcomer Checklist',
        24,
        800,
        438,
        192,
        {
          title: 'NEWCOMER CHECKLIST',
          accentColor: ink,
          items: [
            'Review official orientation information',
            'Confirm your account setup',
            'Read official health coverage guidance',
            'Explore housing and transit resources',
            'Connect with a mentor or community',
          ],
        },
        { ...card, backgroundColor: '#f0f3f5', padding: 12 },
      ),
      section(
        'text',
        'Support Card',
        478,
        800,
        314,
        68,
        { body: 'NEED A HAND?\nExplore official SFU resources.' },
        { ...card, fontWeight: 'bold', padding: 10, color: '#ffffff', backgroundColor: red },
      ),
      section(
        'qr',
        'International Support QR',
        478,
        880,
        112,
        112,
        { radius: 0 },
        { text: 'https://www.sfu.ca/', backgroundColor: '#ffffff', borderWidth: 0 },
      ),
      section(
        'text',
        'Official Guidance',
        602,
        880,
        190,
        112,
        { body: 'QR opens the SFU homepage. Replace with an official resource URL.' },
        { ...plain, padding: 8, fontSize: 16 },
      ),
      section(
        'footer',
        'Footer',
        24,
        1006,
        768,
        30,
        { body: 'SFU PEER MENTOR HUB  ·  ADD YOUR CONTACT DETAILS' },
        { ...card, padding: 7, fontSize: 12, backgroundColor: ink, color: '#ffffff' },
      ),
    ],
  },
];
