import { packImage, section, type PackTemplate } from './packTypes';

const ink = '#082f40';
const red = '#a6192e';
const white = '#ffffff';
const flat = { padding: 12, borderWidth: 0, fontSize: 16, lineHeight: 1.15 };
const plain = { ...flat, backgroundColor: 'transparent' };

/** References 06–10, reconstructed as independent editable sections. */
export const secondTemplates: PackTemplate[] = [
  {
    id: 'event',
    name: 'Workshop / Event — Dark',
    description: 'A charcoal event invitation with essential details, agenda and registration QR.',
    reference: '06_workshop_event_dark.png',
    category: 'Event',
    theme: 'Charcoal / crimson',
    background: '#141719',
    sections: [
      section(
        'text',
        'Brand',
        32,
        20,
        752,
        42,
        { body: 'SFU PEER MENTOR HUB  /  LEARN · CONNECT · GROW', role: 'header' },
        { ...plain, color: white, fontSize: 16, fontWeight: 'bold' },
      ),
      section(
        'hero',
        'Hero Image',
        386,
        76,
        398,
        312,
        { overlay: 0.22, overlayColor: '#101419', radius: 0 },
        { src: packImage('event'), padding: 0, borderWidth: 0 },
      ),
      section(
        'title',
        'Title Banner',
        32,
        92,
        338,
        164,
        { title: 'WORKSHOP /\nEVENT', accentColor: '#141719', radius: 0 },
        {
          ...plain,
          color: '#ffffff',
          fontSize: 48,
          lineHeight: 1.1,
          letterSpacing: -1,
          padding: 8,
        },
      ),
      section(
        'text',
        'Event Introduction',
        32,
        274,
        338,
        114,
        {
          title: 'YOUR EVENT TITLE',
          body: 'A practical session to learn and connect.',
          role: 'header',
        },
        { ...plain, color: '#efb4bd', fontSize: 18 },
      ),
      section(
        'info',
        'Date',
        32,
        404,
        240,
        104,
        {
          title: 'DATE',
          body: 'Date to be confirmed',
          icon: '▦',
          accentColor: '#ff9aaf',
          radius: 0,
        },
        { ...flat, color: white, backgroundColor: '#24282b' },
      ),
      section(
        'info',
        'Time',
        288,
        404,
        240,
        104,
        { title: 'TIME', body: 'Time · Timezone', icon: '◷', accentColor: '#ff9aaf', radius: 0 },
        { ...flat, color: white, backgroundColor: '#24282b' },
      ),
      section(
        'info',
        'Location',
        544,
        404,
        240,
        104,
        {
          title: 'LOCATION',
          body: 'Venue / online link',
          icon: '⌖',
          accentColor: '#ff9aaf',
          radius: 0,
        },
        { ...flat, color: white, backgroundColor: '#24282b' },
      ),
      section(
        'info',
        'Speaker',
        32,
        520,
        240,
        112,
        {
          title: 'SPEAKER / HOST',
          body: 'Add host details\nRole or organization',
          accentColor: '#ff9aaf',
          radius: 0,
        },
        { ...flat, color: white, backgroundColor: '#24282b' },
      ),
      section(
        'info',
        'Description',
        288,
        520,
        496,
        112,
        {
          title: 'ABOUT THE SESSION',
          body: 'Introduce the session, its topic and what participants can expect.',
          accentColor: '#ff9aaf',
          radius: 0,
        },
        { ...flat, color: white, backgroundColor: '#24282b' },
      ),
      section(
        'checklist',
        'Why Join',
        32,
        646,
        240,
        198,
        {
          title: 'WHY JOIN?',
          items: ['Build a useful skill', 'Meet other students', 'Share your questions'],
          accentColor: '#ffffff',
          radius: 0,
        },
        { ...flat, color: white, backgroundColor: '#841329' },
      ),
      section(
        'list',
        'What You Will Learn',
        288,
        646,
        240,
        198,
        {
          title: "WHAT YOU'LL LEARN",
          items: ['Learning outcome one', 'Learning outcome two', 'A practical next step'],
          accentColor: white,
          radius: 0,
        },
        { ...flat, color: white, backgroundColor: '#24282b' },
      ),
      section(
        'list',
        'Who Should Attend',
        544,
        646,
        240,
        198,
        {
          title: 'WHO SHOULD ATTEND?',
          items: ['Describe the audience', 'Add any preparation'],
          accentColor: white,
          radius: 0,
        },
        { ...flat, color: white, backgroundColor: '#24282b' },
      ),
      section(
        'qr',
        'Registration QR',
        32,
        860,
        128,
        128,
        { body: 'https://www.sfu.ca/', radius: 0 },
        { text: 'https://www.sfu.ca/', padding: 0, borderWidth: 0 },
      ),
      section(
        'info',
        'Registration',
        174,
        858,
        210,
        130,
        {
          title: 'REGISTER',
          body: 'Set the QR to your official event registration link.',
          accentColor: white,
          radius: 0,
        },
        { ...flat, color: white, backgroundColor: '#841329' },
      ),
      section(
        'list',
        'Agenda',
        400,
        858,
        384,
        130,
        {
          title: 'AGENDA',
          items: [
            'Welcome and introductions',
            'Activity and discussion',
            'Questions and next steps',
          ],
          accentColor: white,
          radius: 0,
        },
        { ...flat, color: white, backgroundColor: '#24282b' },
      ),
      section(
        'footer',
        'Footer',
        32,
        1000,
        752,
        32,
        { body: 'Peer Mentor Hub  ·  Add contact details before sharing.' },
        { ...plain, color: '#c8cfd3', fontSize: 13, padding: 8 },
      ),
    ],
  },
  {
    id: 'welcome-campus',
    name: 'Welcome to SFU — Campus',
    description: 'An airy campus welcome with four themes, six resource cards and an editable QR.',
    reference: '07_welcome_to_sfu_photo.png',
    category: 'Welcome',
    theme: 'Sky / burgundy',
    background: '#f8fbfd',
    sections: [
      section(
        'text',
        'Brand',
        32,
        20,
        752,
        32,
        { body: 'SFU PEER MENTOR HUB', role: 'header' },
        { ...plain, padding: 6, color: ink, fontWeight: 'bold' },
      ),
      section(
        'hero',
        'Hero Image',
        32,
        64,
        752,
        232,
        { radius: 0 },
        { src: packImage('campus'), padding: 0, borderWidth: 0 },
      ),
      section(
        'title',
        'Title Banner',
        32,
        308,
        752,
        82,
        { title: 'WELCOME TO SFU!', accentColor: '#ffffff', bannerStyle: 'brush' },
        { ...flat, padding: 12, fontSize: 46, color: red, backgroundColor: '#e4f2f8' },
      ),
      section(
        'info',
        'Learn',
        32,
        404,
        176,
        142,
        {
          title: 'LEARN',
          icon: '◇',
          body: 'Explore your learning interests.',
          accentColor: '#104664',
          radius: 18,
        },
        { ...flat, color: ink, backgroundColor: '#e6f2fc', align: 'center' },
      ),
      section(
        'info',
        'Belong',
        224,
        404,
        176,
        142,
        {
          title: 'BELONG',
          icon: '◎',
          body: 'Connect with your campus community.',
          accentColor: '#861633',
          radius: 18,
        },
        { ...flat, color: ink, backgroundColor: '#fae9ee', align: 'center' },
      ),
      section(
        'info',
        'Explore',
        416,
        404,
        176,
        142,
        {
          title: 'EXPLORE',
          icon: '↗',
          body: 'Find places and opportunities.',
          accentColor: '#096061',
          radius: 18,
        },
        { ...flat, color: ink, backgroundColor: '#e6f4f1', align: 'center' },
      ),
      section(
        'info',
        'Make an Impact',
        608,
        404,
        176,
        142,
        {
          title: 'CONTRIBUTE',
          icon: '✧',
          body: 'Share your ideas and interests.',
          accentColor: '#245b39',
          radius: 18,
        },
        { ...flat, color: ink, backgroundColor: '#edf4e7', align: 'center' },
      ),
      section(
        'text',
        'Key Resources',
        32,
        558,
        752,
        38,
        { body: 'KEY RESOURCES TO GET STARTED' },
        { ...plain, color: ink, fontSize: 22, fontWeight: 'bold', padding: 6 },
      ),
      section(
        'info',
        'mySFU',
        32,
        608,
        368,
        88,
        {
          title: 'mySFU',
          body: 'Add a student portal resource.',
          icon: '▤',
          accentColor: '#104664',
        },
        { ...flat, padding: 10, color: ink, backgroundColor: '#e8f2f8' },
      ),
      section(
        'info',
        'Learn About SFU',
        416,
        608,
        368,
        88,
        {
          title: 'LEARN ABOUT SFU',
          body: 'Add a campus information resource.',
          icon: '↗',
          accentColor: '#245b39',
        },
        { ...flat, padding: 10, color: ink, backgroundColor: '#e8f2f8' },
      ),
      section(
        'info',
        'SFU Email',
        32,
        704,
        368,
        88,
        {
          title: 'SFU EMAIL',
          body: 'Add an official email help resource.',
          icon: '✉',
          accentColor: '#104664',
        },
        { ...flat, padding: 10, color: ink, backgroundColor: '#e8f2f8' },
      ),
      section(
        'info',
        'Library',
        416,
        704,
        368,
        88,
        { title: 'LIBRARY', body: 'Add a library resource.', icon: '▤', accentColor: '#104664' },
        { ...flat, padding: 10, color: ink, backgroundColor: '#e8f2f8' },
      ),
      section(
        'info',
        'Student Advising',
        32,
        800,
        368,
        88,
        {
          title: 'STUDENT ADVISING',
          body: 'Add an academic advising resource.',
          icon: '◇',
          accentColor: '#104664',
        },
        { ...flat, padding: 10, color: ink, backgroundColor: '#e8f2f8' },
      ),
      section(
        'info',
        'Health and Wellbeing',
        416,
        800,
        368,
        88,
        {
          title: 'HEALTH & WELLBEING',
          body: 'Add an official support resource.',
          icon: '♡',
          accentColor: '#861633',
        },
        { ...flat, padding: 10, color: ink, backgroundColor: '#e8f2f8' },
      ),
      section(
        'qr',
        'Explore Resources QR',
        32,
        904,
        104,
        104,
        { body: 'https://www.sfu.ca/', radius: 0 },
        { text: 'https://www.sfu.ca/', padding: 0, borderWidth: 0 },
      ),
      section(
        'text',
        'Resource Link',
        146,
        908,
        638,
        78,
        {
          title: 'EXPLORE MORE',
          body: 'Choose a Resource Hub card or update this QR destination.',
        },
        { ...plain, color: ink, fontSize: 18 },
      ),
      section(
        'footer',
        'Footer',
        146,
        992,
        638,
        36,
        { body: 'Peer Mentor Hub  ·  Add your contact details.' },
        { ...plain, color: red, fontSize: 13, padding: 8 },
      ),
    ],
  },
  {
    id: 'deadlines',
    name: 'Important Deadlines — Timeline',
    description: 'Seven editable date rows with support cards and a source QR. Confirm every date.',
    reference: '08_important_deadlines_timeline.png',
    category: 'Planning',
    theme: 'Burgundy / blush',
    background: '#faf0f1',
    sections: [
      section(
        'text',
        'Brand',
        32,
        20,
        752,
        36,
        { body: 'SFU PEER MENTOR HUB  /  PLAN YOUR TERM', role: 'header' },
        { ...plain, color: red, fontWeight: 'bold', padding: 8 },
      ),
      section(
        'title',
        'Title Banner',
        32,
        76,
        548,
        136,
        { title: 'IMPORTANT\nDEADLINES', accentColor: '#a6192e', bannerStyle: 'brush' },
        { ...flat, color: white, fontSize: 42, lineHeight: 1.1, backgroundColor: '#faf0f1' },
      ),
      section(
        'text',
        'Timeline Introduction',
        596,
        76,
        188,
        136,
        { body: 'Add verified dates and a clear next step.', role: 'header' },
        { ...plain, fontSize: 22, color: '#861633', align: 'center', padding: 14 },
      ),
      ...[
        ['Term Begins', 'Confirm the first day of classes.'],
        ['Add / Drop', 'Check the applicable add and drop dates.'],
        ['Holiday / Closure', 'Confirm any changes to classes and services.'],
        ['Withdrawal', 'Confirm the deadline and required steps.'],
        ['Reading Break', 'Confirm whether a break applies to this term.'],
        ['Last Day of Classes', 'Check the official term schedule.'],
        ['Final Exams', 'Confirm your individual exam schedule.'],
      ].map(([label, body], index) =>
        section(
          'highlight',
          `Timeline — ${label}`,
          32,
          222 + index * 80,
          752,
          74,
          {
            title: `DATE TO CONFIRM  ·  ${label.toUpperCase()}`,
            body,
            accentColor: red,
            radius: 10,
          },
          {
            ...flat,
            fontSize: 16,
            padding: 10,
            color: ink,
            backgroundColor: index % 2 ? '#f7e1e4' : '#ffffff',
          },
        ),
      ),
      section(
        'info',
        'Check Important Dates',
        32,
        790,
        240,
        126,
        {
          title: 'CHECK DATES',
          body: 'Use the official academic calendar before sharing.',
          icon: '▦',
          accentColor: red,
          radius: 14,
        },
        { ...flat, color: '#431824', backgroundColor: '#f5dade', align: 'center' },
      ),
      section(
        'info',
        'Get Reminders',
        288,
        790,
        240,
        126,
        {
          title: 'SET REMINDERS',
          body: 'Add confirmed dates to your own calendar.',
          icon: '◷',
          accentColor: red,
          radius: 14,
        },
        { ...flat, color: '#431824', backgroundColor: '#f5dade', align: 'center' },
      ),
      section(
        'info',
        'Need Help',
        544,
        790,
        240,
        126,
        {
          title: 'NEED HELP?',
          body: 'Choose a relevant advising or support resource.',
          icon: '?',
          accentColor: red,
          radius: 14,
        },
        { ...flat, color: '#431824', backgroundColor: '#f5dade', align: 'center' },
      ),
      section(
        'qr',
        'Official Calendar QR',
        32,
        928,
        100,
        100,
        { body: 'https://www.sfu.ca/students/calendar.html', radius: 0 },
        { text: 'https://www.sfu.ca/students/calendar.html', padding: 0, borderWidth: 0 },
      ),
      section(
        'footer',
        'Footer',
        148,
        940,
        636,
        76,
        { body: 'SFU Academic Calendar\nConfirm every date and requirement before sharing.' },
        { ...flat, fontSize: 14, color: white, backgroundColor: '#8a142b' },
      ),
    ],
  },
  {
    id: 'library-campus',
    name: 'SFU Library — Campus',
    description:
      'A photographic library guide with four service sections, an hours table and source QR.',
    reference: '09_sfu_library_photo.png',
    category: 'Campus',
    theme: 'Teal / sky',
    background: '#f7fcfd',
    sections: [
      section(
        'text',
        'Brand',
        32,
        20,
        752,
        32,
        { body: 'SFU PEER MENTOR HUB', role: 'header' },
        { ...plain, padding: 6, fontWeight: 'bold', color: ink },
      ),
      section(
        'title',
        'Title Banner',
        32,
        64,
        752,
        74,
        { title: 'SFU LIBRARY', accentColor: '#f7fcfd', radius: 0 },
        { ...plain, fontSize: 46, padding: 8, color: ink },
      ),
      section(
        'text',
        'Library Introduction',
        32,
        150,
        752,
        48,
        { body: 'Spaces. Resources. Support for your studies.', role: 'header' },
        { ...plain, color: ink, fontSize: 21, fontWeight: 'bold', padding: 8 },
      ),
      section(
        'hero',
        'Hero Image',
        32,
        210,
        752,
        220,
        { radius: 0 },
        { src: packImage('library'), padding: 0, borderWidth: 0 },
      ),
      section(
        'info',
        'Study Spaces',
        32,
        450,
        408,
        112,
        {
          title: 'STUDY SPACES',
          body: 'Add a verified quiet study or group space resource.',
          icon: '▤',
          accentColor: red,
        },
        { ...flat, color: ink, backgroundColor: '#ffffff' },
      ),
      section(
        'info',
        'Research Support',
        32,
        574,
        408,
        112,
        {
          title: 'RESEARCH SUPPORT',
          body: 'Choose an official research help resource.',
          icon: '◇',
          accentColor: '#075863',
        },
        { ...flat, color: ink, backgroundColor: '#ffffff' },
      ),
      section(
        'info',
        'Workshops',
        32,
        698,
        408,
        112,
        {
          title: 'WORKSHOPS',
          body: 'Add an upcoming workshop after confirming its details.',
          icon: '◎',
          accentColor: red,
        },
        { ...flat, color: ink, backgroundColor: '#ffffff' },
      ),
      section(
        'info',
        'Tech and Equipment',
        32,
        822,
        408,
        112,
        {
          title: 'TECH & EQUIPMENT',
          body: 'Add an equipment or borrowing resource.',
          icon: '⌘',
          accentColor: '#075863',
        },
        { ...flat, color: ink, backgroundColor: '#ffffff' },
      ),
      section(
        'table',
        'Library Hours',
        458,
        450,
        326,
        290,
        {
          title: 'LIBRARY HOURS',
          subtitle: 'Confirm current hours online.',
          columns: ['Campus', 'Hours'],
          rows: [
            ['Burnaby', 'Check online'],
            ['Surrey', 'Check online'],
            ['Vancouver', 'Check online'],
          ],
          accentColor: '#075863',
          headerColor: '#075863',
          rowColor: '#dfedf3',
          radius: 14,
        },
        { ...flat, color: ink, backgroundColor: '#edf5fa' },
      ),
      section(
        'qr',
        'Library Resource QR',
        458,
        756,
        128,
        128,
        { body: 'https://www.lib.sfu.ca/', radius: 0 },
        { text: 'https://www.lib.sfu.ca/', padding: 0, borderWidth: 0 },
      ),
      section(
        'info',
        'Official Source',
        600,
        756,
        184,
        178,
        {
          title: 'FIND OUT MORE',
          body: 'Visit SFU Library for current resources and service details.',
          accentColor: '#075863',
          radius: 12,
        },
        { ...flat, color: ink, backgroundColor: '#edf5fa' },
      ),
      section(
        'image',
        'Footer Landscape',
        32,
        950,
        280,
        74,
        { role: 'footer', radius: 0, overlay: 0.18, overlayColor: '#003e43' },
        { src: packImage('mountain'), padding: 0, borderWidth: 0 },
      ),
      section(
        'footer',
        'Footer',
        328,
        950,
        456,
        74,
        { body: 'Peer Mentor Hub\nAdd a verified source and contact details.' },
        { ...flat, fontSize: 14, color: white, backgroundColor: '#07515a', padding: 14 },
      ),
    ],
  },
  {
    id: 'wellbeing',
    name: 'Student Wellbeing',
    description:
      'A mountain hero and six warm support cards, with a balance checklist and resource QR.',
    reference: '10_student_wellbeing.png',
    category: 'Wellbeing',
    theme: 'Rose / forest / sky',
    background: '#fff5ee',
    sections: [
      section(
        'text',
        'Brand',
        32,
        20,
        752,
        32,
        { body: 'SFU PEER MENTOR HUB', role: 'header' },
        { ...plain, padding: 6, color: red, fontWeight: 'bold' },
      ),
      section(
        'title',
        'Title Banner',
        32,
        64,
        752,
        136,
        { title: 'STUDENT\nWELLBEING', accentColor: '#fff5ee', radius: 0 },
        { ...plain, color: '#85182e', fontSize: 48, lineHeight: 1.1, padding: 8 },
      ),
      section(
        'text',
        'Wellbeing Introduction',
        32,
        210,
        752,
        48,
        { body: 'Make space for your wellbeing throughout university.', role: 'header' },
        { ...plain, color: ink, fontSize: 21, padding: 8 },
      ),
      section(
        'hero',
        'Hero Image',
        32,
        270,
        752,
        220,
        { radius: 0 },
        { src: packImage('wellbeing'), padding: 0, borderWidth: 0 },
      ),
      section(
        'info',
        'Mental Health',
        32,
        504,
        240,
        180,
        {
          title: 'MENTAL HEALTH',
          body: 'Add an official counselling or wellbeing resource.',
          icon: '♡',
          accentColor: '#8e1934',
          radius: 14,
        },
        { ...flat, color: ink, backgroundColor: '#f9e6e8', align: 'center' },
      ),
      section(
        'info',
        'Physical Health',
        288,
        504,
        240,
        180,
        {
          title: 'PHYSICAL HEALTH',
          body: 'Add a health service or recreation resource.',
          icon: '+',
          accentColor: '#125371',
          radius: 14,
        },
        { ...flat, color: ink, backgroundColor: '#e8f3fa', align: 'center' },
      ),
      section(
        'info',
        'Peer Support',
        544,
        504,
        240,
        180,
        {
          title: 'PEER SUPPORT',
          body: 'Share a student community or peer connection.',
          icon: '◎',
          accentColor: '#245b39',
          radius: 14,
        },
        { ...flat, color: ink, backgroundColor: '#eef2e6', align: 'center' },
      ),
      section(
        'info',
        'Stress Management',
        32,
        696,
        240,
        180,
        {
          title: 'STRESS MANAGEMENT',
          body: 'Add a useful support resource or a personal reminder.',
          icon: '◇',
          accentColor: '#245b39',
          radius: 14,
        },
        { ...flat, color: ink, backgroundColor: '#eaf1e8', align: 'center' },
      ),
      section(
        'checklist',
        'Build Balance',
        288,
        696,
        240,
        180,
        {
          title: 'BUILD BALANCE',
          items: ['Plan a small break', 'Make time to rest', 'Connect with someone'],
          icon: '☀',
          accentColor: '#87501a',
          radius: 14,
        },
        { ...flat, color: ink, backgroundColor: '#fff0d8' },
      ),
      section(
        'info',
        'Support',
        544,
        696,
        240,
        180,
        {
          title: "YOU'RE NOT ALONE",
          body: 'Choose an official support resource or contact your Peer Mentor.',
          icon: '♡',
          accentColor: '#8e1934',
          radius: 14,
        },
        { ...flat, color: ink, backgroundColor: '#fae7e5', align: 'center' },
      ),
      section(
        'qr',
        'Wellbeing Resource QR',
        32,
        890,
        110,
        110,
        { body: 'https://www.sfu.ca/students/health.html', radius: 0 },
        { text: 'https://www.sfu.ca/students/health.html', padding: 0, borderWidth: 0 },
      ),
      section(
        'info',
        'Find Support',
        156,
        890,
        628,
        84,
        {
          title: 'FIND WELLBEING RESOURCES',
          body: 'Update the QR with your chosen official support resource.',
          accentColor: '#8e1934',
          radius: 12,
        },
        { ...flat, color: ink, backgroundColor: '#fce3dd' },
      ),
      section(
        'footer',
        'Footer',
        156,
        990,
        628,
        34,
        { body: 'Peer Mentor Hub  ·  Add your contact details.' },
        { ...plain, color: '#85182e', fontSize: 13, padding: 8 },
      ),
    ],
  },
];
