import { packImage, section, type PackTemplate } from './packTypes';

const red = '#a6192e';
const navy = '#12334e';
const white = '#ffffff';
const card = { fontSize: 16, lineHeight: 1.15, padding: 12, color: navy, borderColor: '#cbd8e3' };
const hero = (scene: string, x: number, y: number, w: number, h: number, radius = 8) =>
  section(
    'hero',
    'Hero Image',
    x,
    y,
    w,
    h,
    { radius },
    { src: packImage(scene), padding: 0, borderWidth: 0 },
  );
const footer = (body: string, background = red) =>
  section(
    'footer',
    'Footer',
    24,
    986,
    768,
    46,
    { body, radius: 0 },
    {
      fontSize: 14,
      lineHeight: 1.15,
      padding: 14,
      color: white,
      backgroundColor: background,
      borderWidth: 0,
    },
  );

/** References 01–05, reconstructed from independently editable section content. */
export const firstTemplates: PackTemplate[] = [
  {
    id: 'newsletter',
    name: 'Weekly Check-In Newsletter',
    description: 'Weekly updates, recreation schedules, planning and quick tips in two columns.',
    reference: '01_weekly_checkin_newsletter.png',
    category: 'Weekly',
    theme: 'Mountain newsletter',
    background: '#ffffff',
    sections: [
      hero('mountain', 24, 24, 768, 180),
      section(
        'title',
        'Title Banner',
        24,
        216,
        768,
        72,
        { title: 'WEEKLY CHECK-IN', bannerStyle: 'brush', accentColor: red, radius: 0 },
        { fontSize: 40, lineHeight: 1.1, padding: 12, color: white, borderWidth: 0 },
      ),
      section(
        'greeting',
        'Greeting',
        24,
        300,
        768,
        46,
        { body: 'Hope your week is going well, {{recipientName}}!', radius: 24 },
        { ...card, backgroundColor: '#eef3f8', align: 'center', fontSize: 18, borderWidth: 0 },
      ),
      section(
        'text',
        'Intro',
        24,
        355,
        768,
        38,
        { body: 'A few updates, opportunities and reminders for the week ahead.', role: 'header' },
        { ...card, padding: 8, align: 'center', borderWidth: 0 },
      ),
      section(
        'highlight',
        'Announcement',
        24,
        404,
        768,
        106,
        {
          title: 'IMPORTANT DATE',
          subtitle: 'Event or occasion · Add date and location',
          body: 'Add a verified announcement and one clear next step.',
          accentColor: red,
        },
        { ...card, backgroundColor: '#fdebea', fontSize: 18 },
      ),
      section(
        'list',
        'Get Involved',
        24,
        522,
        378,
        222,
        {
          title: 'GET INVOLVED',
          subtitle: 'Discover more than your classes.',
          items: [
            'Club or event to explore',
            'A volunteering opportunity',
            'A way to meet new people',
            'Add a campus resource',
          ],
          accentColor: red,
          icon: '↗',
        },
        { ...card },
      ),
      section(
        'schedule',
        'Recreation',
        414,
        522,
        378,
        222,
        {
          title: 'TRY RECREATION',
          subtitle: 'Add a verified drop-in schedule.',
          columns: ['Activity', 'Day', 'Time', 'Place'],
          rows: [
            ['Activity 1', 'Day', 'Time', 'Room'],
            ['Activity 2', 'Day', 'Time', 'Room'],
            ['Activity 3', 'Day', 'Time', 'Room'],
          ],
          columnAlign: ['left', 'left', 'left', 'left'],
          accentColor: red,
          headerColor: navy,
          rowColor: '#edf2f8',
        },
        { ...card },
      ),
      section(
        'table',
        'Course Planning',
        24,
        756,
        378,
        218,
        {
          title: 'PLAN AHEAD',
          subtitle: 'Sample planning table · Edit all details',
          columns: ['Course', 'Instructor'],
          rows: [
            ['Course code', 'Instructor'],
            ['Course code', 'Instructor'],
            ['Course code', 'Instructor'],
          ],
          accentColor: red,
          headerColor: navy,
          rowColor: '#edf2f8',
        },
        { ...card },
      ),
      section(
        'list',
        'Planning Tips',
        414,
        756,
        378,
        218,
        {
          title: 'QUICK TIPS',
          subtitle: 'Small steps for the week ahead.',
          items: [
            'Visit office hours early',
            'Plan time for a break',
            'Explore a campus resource',
            'Connect with your Peer Mentor',
          ],
          accentColor: red,
          icon: '✓',
        },
        { ...card },
      ),
      footer('Questions? Message your Peer Mentor · Add your contact details'),
    ],
  },
  {
    id: 'welcome',
    name: 'Welcome to SFU Orientation',
    description: 'Introduce your mentor, languages, first steps and ways to connect.',
    reference: '02_welcome_to_sfu_orientation.png',
    category: 'Welcome',
    theme: 'Red orientation',
    background: '#ffffff',
    sections: [
      hero('mountain', 24, 24, 768, 210),
      section(
        'title',
        'Title Banner',
        24,
        246,
        768,
        78,
        { title: 'WELCOME TO SFU', bannerStyle: 'brush', accentColor: red, radius: 0 },
        { fontSize: 43, lineHeight: 1.1, padding: 12, color: white, borderWidth: 0 },
      ),
      section(
        'info',
        'Mentor Introduction',
        174,
        340,
        228,
        242,
        {
          title: 'YOUR PEER MENTOR',
          body: 'Hello! I am here to help you get started.\n\nAdd your program, interests and a short introduction.',
          accentColor: red,
        },
        { ...card, backgroundColor: '#f6f9fc' },
      ),
      section(
        'image',
        'Mentor Photo',
        24,
        340,
        138,
        242,
        { fitMode: 'cover', radius: 14 },
        { src: packImage('portrait'), padding: 0, borderWidth: 0 },
      ),
      section(
        'info',
        'Languages',
        414,
        340,
        378,
        142,
        {
          title: 'I SPEAK',
          body: 'Add the languages you are comfortable using.\n\nLet us find a way to connect.',
          icon: '◎',
          accentColor: red,
        },
        { ...card, backgroundColor: '#edf3fa' },
      ),
      section(
        'checklist',
        'First Steps',
        24,
        596,
        378,
        378,
        {
          title: 'IMPORTANT FIRST STEPS',
          subtitle: 'Choose a few things to get started.',
          items: [
            'Explore your Computing ID',
            'Find SFU Card information',
            'Check transit information',
            'Look through your course plan',
            'Explore a club or event',
            'Ask your Peer Mentor a question',
          ],
          accentColor: red,
          icon: '✓',
        },
        { ...card, backgroundColor: '#f5f8fc', fontSize: 17 },
      ),
      section(
        'list',
        'How I Can Help',
        414,
        496,
        378,
        232,
        {
          title: 'HOW I CAN HELP',
          items: [
            'Finding campus resources',
            'Adjusting to university life',
            'Exploring clubs and events',
            'Preparing questions for an advisor',
            'Finding your community',
          ],
          accentColor: red,
          icon: '♡',
        },
        { ...card },
      ),
      section(
        'info',
        'Contact',
        414,
        742,
        246,
        232,
        {
          title: 'CONTACT ME',
          body: 'Add your preferred contact details.\n\nAdd your availability and meeting location.\n\nEdit the QR link to connect.',
          accentColor: red,
          icon: '✉',
        },
        { ...card, backgroundColor: '#fff0ee' },
      ),
      section(
        'qr',
        'Contact QR',
        674,
        792,
        118,
        118,
        { body: 'https://www.sfu.ca/', radius: 8 },
        { text: 'https://www.sfu.ca/', padding: 0, borderWidth: 0 },
      ),
      footer('Peer Mentor Hub · Students supporting students'),
    ],
  },
  {
    id: 'courses',
    name: 'Course Planning — Classic',
    description: 'A detailed course table, term selection and a practical enrolment checklist.',
    reference: '03_course_planning_blue.png',
    category: 'Planning',
    theme: 'Classic navy and red',
    background: '#f9fbfd',
    sections: [
      hero('mountain', 24, 24, 768, 170),
      section(
        'title',
        'Title Banner',
        24,
        206,
        768,
        80,
        { title: 'COURSE PLANNING', bannerStyle: 'brush', accentColor: red, radius: 0 },
        { fontSize: 43, lineHeight: 1.1, padding: 12, color: white, borderWidth: 0 },
      ),
      section(
        'highlight',
        'Term',
        24,
        300,
        440,
        96,
        { title: 'SELECT TERM', body: 'Add the term you are planning for.', accentColor: navy },
        { ...card, backgroundColor: '#e7eef6', fontSize: 18 },
      ),
      section(
        'table',
        'Course Offerings',
        24,
        408,
        440,
        520,
        {
          title: 'COURSE OFFERINGS',
          subtitle: 'Sample rows · Replace with Course Planner data',
          columns: ['Course', 'Title', 'Instructor'],
          rows: [
            ['SUBJ 101', 'Course title', 'To confirm'],
            ['SUBJ 102', 'Course title', 'To confirm'],
            ['SUBJ 201', 'Course title', 'To confirm'],
            ['SUBJ 202', 'Course title', 'To confirm'],
            ['SUBJ 301', 'Course title', 'To confirm'],
            ['SUBJ 302', 'Course title', 'To confirm'],
            ['SUBJ 401', 'Course title', 'To confirm'],
            ['SUBJ 402', 'Course title', 'To confirm'],
          ],
          columnAlign: ['left', 'left', 'left'],
          accentColor: red,
          headerColor: navy,
          rowColor: '#eaf0f6',
        },
        { ...card, padding: 14, lineHeight: 1.2, fontSize: 18 },
      ),
      section(
        'list',
        'Plan Ahead',
        478,
        300,
        314,
        180,
        {
          title: 'PLAN AHEAD',
          items: [
            'Explore your course options',
            'Build a balanced schedule',
            'Keep a backup option',
          ],
          accentColor: red,
        },
        { ...card, backgroundColor: '#fff0ee', fontSize: 17 },
      ),
      section(
        'checklist',
        'Before You Enrol',
        478,
        492,
        314,
        260,
        {
          title: 'BEFORE YOU ENROL',
          items: [
            'Check course prerequisites',
            'Confirm program requirements',
            'Review class format and times',
            'Check for schedule conflicts',
            'Prepare questions for an advisor',
          ],
          accentColor: red,
          icon: '✓',
        },
        { ...card, fontSize: 17 },
      ),
      section(
        'list',
        'Planning Tips',
        478,
        764,
        314,
        164,
        {
          title: 'WHY PLAN AHEAD?',
          items: [
            'Connect courses to your goals',
            'Allow time to explore',
            'Confirm details with SFU',
          ],
          accentColor: navy,
        },
        { ...card },
      ),
      section(
        'qr',
        'Course Information QR',
        692,
        940,
        100,
        100,
        { body: 'https://www.sfu.ca/', radius: 0, role: 'footer' },
        { text: 'https://www.sfu.ca/', padding: 0, borderWidth: 0 },
      ),
      section(
        'footer',
        'Footer',
        24,
        940,
        656,
        96,
        {
          title: 'YOUR NEXT TERM',
          body: 'Offerings and schedules may change.\nConfirm final details with official SFU sources.',
          radius: 0,
        },
        {
          color: white,
          backgroundColor: red,
          fontSize: 16,
          lineHeight: 1.15,
          padding: 14,
          borderWidth: 0,
        },
      ),
    ],
  },
  {
    id: 'library',
    name: 'Library Guide — Editorial',
    description: 'An editorial guide to study spaces, research support, floors and bookable rooms.',
    reference: '04_library_guide_editorial.png',
    category: 'Academic',
    theme: 'Cream editorial',
    background: '#f7f4ee',
    sections: [
      section(
        'text',
        'Brand',
        24,
        24,
        768,
        40,
        { body: 'PEER MENTOR HUB  /  STUDENTS SUPPORTING STUDENTS', role: 'header' },
        { ...card, padding: 10, letterSpacing: 2, backgroundColor: 'transparent', borderWidth: 0 },
      ),
      hero('library', 24, 76, 768, 225, 0),
      section(
        'title',
        'Title Banner',
        24,
        313,
        768,
        90,
        { title: 'LIBRARY GUIDE', bannerStyle: 'underline', accentColor: navy, radius: 0 },
        {
          fontSize: 60,
          fontFamily: 'Georgia',
          lineHeight: 1.05,
          padding: 8,
          color: navy,
          backgroundColor: 'transparent',
          borderWidth: 0,
          align: 'center',
        },
      ),
      section(
        'text',
        'Subtitle',
        24,
        411,
        768,
        34,
        { body: 'SPACES  /  RESOURCES  /  SUPPORT  /  YOUR SUCCESS', role: 'header' },
        {
          ...card,
          padding: 7,
          fontSize: 16,
          align: 'center',
          letterSpacing: 1,
          backgroundColor: 'transparent',
          borderWidth: 0,
        },
      ),
      section(
        'info',
        'Quiet Spaces',
        24,
        459,
        180,
        158,
        {
          title: 'QUIET SPACES',
          body: 'Add a short guide to your preferred study spaces.',
          accentColor: red,
          radius: 0,
        },
        { ...card, backgroundColor: 'transparent', borderWidth: 0 },
      ),
      section(
        'info',
        'Group Study',
        220,
        459,
        180,
        158,
        {
          title: 'GROUP STUDY',
          body: 'Add details about places to work together.',
          accentColor: red,
          radius: 0,
        },
        { ...card, backgroundColor: 'transparent', borderWidth: 0 },
      ),
      section(
        'info',
        'Research Help',
        416,
        459,
        180,
        158,
        {
          title: 'RESEARCH HELP',
          body: 'Choose a research support resource to share.',
          accentColor: red,
          radius: 0,
        },
        { ...card, backgroundColor: 'transparent', borderWidth: 0 },
      ),
      section(
        'info',
        'Quick Tips',
        612,
        459,
        180,
        158,
        {
          title: 'QUICK TIPS',
          body: 'Add one useful tip for your next library visit.',
          accentColor: red,
          radius: 0,
        },
        { ...card, backgroundColor: 'transparent', borderWidth: 0 },
      ),
      section(
        'table',
        'Floor Guide',
        24,
        631,
        430,
        324,
        {
          title: 'FLOOR GUIDE',
          columns: ['Floor', 'Use'],
          rows: [
            ['Floor / area', 'Add study style'],
            ['Floor / area', 'Add study style'],
            ['Floor / area', 'Add study style'],
            ['Floor / area', 'Add study style'],
            ['Floor / area', 'Add study style'],
          ],
          accentColor: navy,
          headerColor: navy,
          rowColor: '#e9e5de',
          radius: 0,
        },
        { ...card, backgroundColor: '#f7f4ee', padding: 14, fontSize: 17 },
      ),
      section(
        'list',
        'Bookable Rooms',
        470,
        631,
        322,
        196,
        {
          title: 'BOOKABLE ROOMS',
          items: ['Capacity: add details', 'Location: add details', 'Booking: add official link'],
          accentColor: red,
          radius: 0,
        },
        { ...card, backgroundColor: '#eee2dc', fontSize: 17 },
      ),
      section(
        'info',
        'Official Source',
        470,
        839,
        210,
        116,
        {
          title: 'OFFICIAL SOURCE',
          body: 'Edit the QR to link to the official library page.',
          accentColor: navy,
          radius: 0,
        },
        { ...card, backgroundColor: 'transparent', borderWidth: 0 },
      ),
      section(
        'qr',
        'Library QR',
        692,
        839,
        100,
        100,
        { body: 'https://www.lib.sfu.ca/', radius: 0 },
        { text: 'https://www.lib.sfu.ca/', padding: 0, borderWidth: 0 },
      ),
      section(
        'footer',
        'Footer',
        24,
        973,
        768,
        59,
        {
          body: 'Add your contact details  ·  Official library links  ·  Meeting location',
          radius: 0,
        },
        {
          fontSize: 14,
          lineHeight: 1.15,
          padding: 18,
          color: navy,
          backgroundColor: '#e8e0d6',
          borderWidth: 0,
        },
      ),
    ],
  },
  {
    id: 'essentials',
    name: 'Student Essentials — Playful',
    description:
      'A cheerful campus starter with three essential cards, a checklist and useful links.',
    reference: '05_student_essentials_playful.png',
    category: 'Welcome',
    theme: 'Playful pastel',
    background: '#fffaf0',
    sections: [
      hero('campus', 24, 24, 768, 180, 60),
      section(
        'text',
        'Brand',
        24,
        218,
        428,
        52,
        { body: 'PEER MENTOR HUB', role: 'header' },
        {
          ...card,
          padding: 12,
          fontSize: 22,
          fontWeight: 'bold',
          backgroundColor: 'transparent',
          borderWidth: 0,
        },
      ),
      section(
        'greeting',
        'Greeting',
        464,
        218,
        328,
        52,
        { body: 'Hi, {{recipientName}}!', radius: 26 },
        {
          ...card,
          padding: 14,
          fontSize: 20,
          color: white,
          backgroundColor: red,
          align: 'center',
          borderWidth: 0,
        },
      ),
      section(
        'title',
        'Title Banner',
        24,
        280,
        768,
        88,
        { title: 'STUDENT', bannerStyle: 'underline', accentColor: red, radius: 0 },
        {
          fontSize: 64,
          lineHeight: 1,
          padding: 8,
          color: red,
          backgroundColor: 'transparent',
          borderWidth: 0,
          align: 'center',
        },
      ),
      section(
        'title',
        'Essentials Banner',
        24,
        378,
        768,
        90,
        { title: 'ESSENTIALS', bannerStyle: 'brush', accentColor: '#d6eff8', radius: 16 },
        {
          fontSize: 64,
          lineHeight: 1,
          padding: 8,
          color: '#006a92',
          backgroundColor: '#fffaf0',
          borderWidth: 0,
          align: 'center',
        },
      ),
      section(
        'info',
        'Computing ID',
        24,
        482,
        244,
        260,
        {
          title: 'COMPUTING ID',
          subtitle: 'Get connected',
          body: 'Add official Computing ID information and a useful next step.\n\nReplace this card with a Resource Hub entry.',
          accentColor: red,
          icon: '⌨',
          radius: 24,
        },
        { ...card, padding: 18, backgroundColor: '#ffe2dc', borderWidth: 0, fontSize: 17 },
      ),
      section(
        'info',
        'SFU Card',
        286,
        482,
        244,
        260,
        {
          title: 'SFU CARD',
          subtitle: 'Get campus-ready',
          body: 'Add official SFU Card information and where to find current instructions.\n\nKeep details concise.',
          accentColor: '#006a92',
          icon: '▣',
          radius: 24,
        },
        { ...card, padding: 18, backgroundColor: '#dcf2fc', borderWidth: 0, fontSize: 17 },
      ),
      section(
        'info',
        'U-Pass',
        548,
        482,
        244,
        260,
        {
          title: 'U-PASS / TRANSIT',
          subtitle: 'Plan your journey',
          body: 'Add official transit information.\n\nCheck current eligibility and instructions before sharing.',
          accentColor: red,
          icon: '↗',
          radius: 24,
        },
        { ...card, padding: 18, backgroundColor: '#ffead9', borderWidth: 0, fontSize: 17 },
      ),
      section(
        'checklist',
        'New Student Checklist',
        24,
        756,
        244,
        224,
        {
          title: 'FIRST STEPS',
          items: [
            'Explore your campus',
            'Find a study space',
            'Review your course plan',
            'Ask a question',
          ],
          accentColor: '#216a4e',
          radius: 24,
        },
        { ...card, backgroundColor: '#e2f1dc', borderWidth: 0, padding: 16 },
      ),
      section(
        'list',
        'Important Links',
        286,
        756,
        244,
        224,
        {
          title: 'IMPORTANT LINKS',
          items: ['SFU main website', 'Academic calendar', 'Student services', 'Campus maps'],
          accentColor: '#006a92',
          radius: 24,
        },
        { ...card, backgroundColor: '#dcf2fc', borderWidth: 0, padding: 16 },
      ),
      section(
        'info',
        'Need Help',
        548,
        756,
        244,
        112,
        {
          title: 'NEED HELP?',
          body: 'Your Peer Mentor can help you find the next step.',
          accentColor: red,
          radius: 24,
        },
        { ...card, backgroundColor: '#ffe2dc', borderWidth: 0, padding: 14 },
      ),
      section(
        'qr',
        'Help QR',
        548,
        882,
        100,
        100,
        { body: 'https://www.sfu.ca/', radius: 8 },
        { text: 'https://www.sfu.ca/', padding: 0, borderWidth: 0 },
      ),
      section(
        'text',
        'Contact',
        660,
        882,
        132,
        98,
        { body: 'Add contact details and availability.' },
        { ...card, padding: 8, backgroundColor: 'transparent', borderWidth: 0 },
      ),
      section(
        'footer',
        'Footer',
        24,
        994,
        768,
        38,
        { body: 'Peer Mentor Hub  ·  Students supporting students', radius: 0 },
        {
          fontSize: 12,
          lineHeight: 1.15,
          padding: 10,
          color: '#216a4e',
          backgroundColor: 'transparent',
          align: 'center',
          borderWidth: 0,
        },
      ),
    ],
  },
];
